services:
  - type: web
    name: telegram_bot
    env: python
    plan: free
    buildCommand: "pip install --upgrade pip setuptools wheel && pip install --prefer-binary -r requirements.txt"
    startCommand: "python main.py"
    envVars:
      - key: PYTHON_VERSION
        value: "3.11"
      - key: TELEGRAM_TOKEN
        value: "${TELEGRAM_TOKEN}"
      - key: ADMIN_ID
        value: "${ADMIN_ID}"
      - key: WEBHOOK_URL
        value: "${WEBHOOK_URL}"
